services:
  - type: web
    name: hesap-paylas-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hesap-paylas-db
          property: connectionString

  - type: postgres
    name: hesap-paylas-db
    ipWhitelist: []
    plan: free
    postgresMajorVersion: 15

